# Generated by Django 3.2.6 on 2021-08-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Spain', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
